# -*- coding: utf-8 -*-
"""AU_label.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vEkCTeMwHx4-dcaydVTbKg_yokQiad8T
"""

import numpy as np
import pandas as pd
array = []
zero_data = np.zeros(22)
print(zero_data)
data = pd.read_csv('D:\\LE\\0309to_csv\\0_frustration_0309.csv')

data = pd.DataFrame(data) 
print('data:',data)
au_label=data['AU']
print('au_label:',au_label)
BP4D_use_AU = ["1", "2", "4", "5", "6", "7", "9", "10", "11", "12", "13", 
               "14", "15", "16", "17", "18", "20", "22", "23", "24",
               "27", "28"]

for indexs in au_label.index:
  c = au_label.loc[indexs]
  print(c)



  
  
